=== skempken/interverdikom/doc/xml_schema/SMPQueue.dtd
<!ELEMENT SMPQueue (ArrivalProcess,ServiceProcess)>
<!ATTLIST SMPQueue
	type (InterArrival|TimeSlotted) #REQUIRED
>

	<!ELEMENT ArrivalProcess (SMProcess)>
	
		<!ELEMENT SMProcess (TransitionMatrix,Distribution+)>
		<!ATTLIST SMProcess
			numStates CDATA #REQUIRED
		>
		
			<!ELEMENT TransitionMatrix (MatrixValue+)>
			
				<!ELEMENT MatrixValue (#PCDATA)>
				<!ATTLIST MatrixValue
					fromState CDATA #REQUIRED
					toState CDATA #REQUIRED
				>
				
			<!ELEMENT Distribution (DistValue)>
			<!ATTLIST Distribution
				stateIndex CDATA #IMPLIED
				steps CDATA #REQUIRED
			>
			
				<!ELEMENT DistValue (#PCDATA)>
				<!ATTLIST DistValue
					steps CDATA #REQUIRED
				>
			
	<!ELEMENT ServiceProcess (GIProcess)>
		<!ELEMENT GIProcess (Distribution+)>

=== skempken/interverdikom/doc/xml_schema/sample.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE SMPQueue PUBLIC "-//InterVerdiKom Team//SMPQueue//EN" "SMPQueue.dtd">

<SMPQueue type="InterArrival">
	<ArrivalProcess>
		<SMProcess numStates="X">
			<TransitionMatrix>
				<MatrixValue fromState="X" toState="Y">
					X
				</MatrixValue>
				<MatrixValue fromState="X" toState="Y">
					X
				</MatrixValue>
			</TransitionMatrix>
			<Distribution stateIndex="X" steps="Y">
				<DistValue steps="X">
					X
				</DistValue>
				<DistValue steps="X">
					X
				</DistValue>
			</Distribution>
		</SMProcess>
	</ArrivalProcess>
</SMPQueue>
